### ISSUE TITLE
hook camera.startPreview方法，切换摄像头时出现crash

### ISSUE THREAD

**Issue by yongyecc** [yongyecc/AndroidAbility#2]
```
05-05 14:34:17.579  7297  7297 E AndroidRuntime: Process: cn.yongye.androidability, PID: 7297
05-05 14:34:17.579  7297  7297 E AndroidRuntime: java.lang.RuntimeException: Camera is being used after Camera.release() was called
05-05 14:34:17.579  7297  7297 E AndroidRuntime: 	at android.hardware.Camera.setHasPreviewCallback(Native Method)
05-05 14:34:17.579  7297  7297 E AndroidRuntime: 	at android.hardware.Camera.access$600(Camera.java:158)
05-05 14:34:17.579  7297  7297 E AndroidRuntime: 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1225)
05-05 14:34:17.579  7297  7297 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-05 14:34:17.579  7297  7297 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
05-05 14:34:17.579  7297  7297 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
05-05 14:34:17.579  7297  7297 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-05 14:34:17.579  7297  7297 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-05 14:34:17.579  7297  7297 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-05 14:34:18.297  7627  7627 W BootstrapClass: 	at de.robv.android.xposed.DexposedBridge.<clinit>(DexposedBridge.java:58)
05-05 14:34:18.297  7627  7627 W BootstrapClass: 	at de.robv.android.xposed.DexposedBridge.hookAllMethods(DexposedBridge.java:163)
```

**Comment by yongyecc** [comment]
fix https://github.com/yongyecc/AndroidAbility/commit/a2d17364fd88276ca53271ee2bfc802394989801
